# -*- coding: utf-8 -*-
"""scraping_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XkLaazJ2PNNInTKGyETz7jjwJ-_8naAq
"""

!pip install google-play-scraper
import pandas as pd
from google_play_scraper import Sort, reviews

# STEP 1: SCRAPING DATA (Kriteria 1)

def scrape_ulasan():
    print("Sedang mengambil data dari Google Play Store...")
    app_id = 'com.kurogame.wutheringwaves.global'


    result, _ = reviews(
        app_id,
        lang='id',
        country='id',
        sort=Sort.NEWEST,
        count=10000
    )

    df = pd.DataFrame(result)

    df_result = df[['content', 'score']]

    df_result.to_csv('dataset_wuthering_waves.csv', index=False)
    print(f"Total data yang didapat dan disimpan: {len(df_result)}")

if __name__ == "__main__":
    scrape_ulasan()